standard_whitelist:
  - WHITE_CARPET
  - STONE_BRICK_STAIRS
  - WARPED_FENCE
  - IRON_TRAPDOOR
  - SUNFLOWER
  - BELL
  - OAK_HANGING_SIGN
  - OAK_SAPLING
  - BRAIN_CORAL
  - RED_NETHER_BRICK_WALL
  - LIME_BANNER
  - WARPED_PRESSURE_PLATE
  - OAK_WALL_SIGN
  - MAGENTA_WALL_BANNER
  - LIGHT_GRAY_BED
  - HORN_CORAL
  - ACACIA_TRAPDOOR
  - END_ROD
  - BAMBOO_MOSAIC_STAIRS
  - COBBLESTONE_WALL
  - MANGROVE_WALL_SIGN
  - FIRE_CORAL_WALL_FAN
  - OAK_STAIRS
  - MAGENTA_STAINED_GLASS_PANE
  - FERN
  - BROWN_STAINED_GLASS_PANE
  - CRIMSON_WALL_HANGING_SIGN
  - POWERED_RAIL
  - REDSTONE_ORE
  - PRISMARINE_STAIRS
  - MAGENTA_BANNER
  - MOSS_CARPET
  - DEAD_BUSH
  - IRON_BARS
  - GRASS
  - LILAC
  - CRIMSON_FENCE
  - BAMBOO_PRESSURE_PLATE
  - BLUE_ORCHID
  - OAK_WALL_HANGING_SIGN
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - BAMBOO_SAPLING
  - CHERRY_TRAPDOOR
  - LIME_CONCRETE_POWDER
  - NETHER_BRICK_FENCE
  - OAK_TRAPDOOR
  - CRIMSON_PRESSURE_PLATE
  - GREEN_CARPET
  - SPRUCE_WALL_HANGING_SIGN
  - BIRCH_DOOR
  - DARK_OAK_WALL_SIGN
  - OAK_SIGN
  - BLACKSTONE_STAIRS
  - CRIMSON_WALL_SIGN
  - PINK_BANNER
  - LIGHT_BLUE_BANNER
  - CHERRY_WALL_SIGN
  - CHERRY_STAIRS
  - MAGENTA_CONCRETE_POWDER
  - END_STONE_BRICK_WALL
  - POLISHED_DEEPSLATE_WALL
  - BLACK_BED
  - MANGROVE_STAIRS
  - STONE_PRESSURE_PLATE
  - BLACKSTONE_WALL
  - LIME_CARPET
  - GRANITE_WALL
  - SMOOTH_SANDSTONE_STAIRS
  - TRIPWIRE_HOOK
  - JUNGLE_PRESSURE_PLATE
  - BUBBLE_CORAL_BLOCK
  - ACACIA_DOOR
  - YELLOW_CONCRETE_POWDER
  - JUNGLE_TRAPDOOR
  - MOSSY_COBBLESTONE_STAIRS
  - ORANGE_CONCRETE_POWDER
  - BROWN_MUSHROOM_BLOCK
  - COBBLESTONE_STAIRS
  - POLISHED_BLACKSTONE_WALL
  - BLUE_CARPET
  - OAK_FENCE
  - SOUL_LANTERN
  - SCULK_VEIN
  - CYAN_STAINED_GLASS_PANE
  - BLACK_STAINED_GLASS_PANE
  - MOSSY_STONE_BRICK_WALL
  - DANDELION
  - TALL_GRASS
  - SUSPICIOUS_GRAVEL
  - BLACK_WALL_BANNER
  - BLUE_STAINED_GLASS_PANE
  - FLOWERING_AZALEA
  - BIRCH_FENCE_GATE
  - PINK_STAINED_GLASS_PANE
  - BAMBOO_TRAPDOOR
  - BLACK_CARPET
  - CHERRY_WALL_HANGING_SIGN
  - PURPUR_STAIRS
  - BRICK_WALL
  - GRINDSTONE
  - POLISHED_DIORITE_STAIRS
  - WAXED_CUT_COPPER_STAIRS
  - TORCH
  - WARPED_TRAPDOOR
  - RED_CARPET
  - RED_BANNER
  - ACACIA_WALL_HANGING_SIGN
  - LARGE_FERN
  - CYAN_BANNER
  - BRAIN_CORAL_WALL_FAN
  - OAK_DOOR
  - CHERRY_SIGN
  - SPRUCE_SIGN
  - CHERRY_PRESSURE_PLATE
  - FIRE_CORAL_BLOCK
  - CYAN_CARPET
  - POLISHED_BLACKSTONE_STAIRS
  - REDSTONE_TORCH
  - RED_SANDSTONE_WALL
  - JUNGLE_BUTTON
  - BIRCH_WALL_SIGN
  - POINTED_DRIPSTONE
  - JUNGLE_SIGN
  - BLACK_BANNER
  - CRIMSON_BUTTON
  - BUBBLE_CORAL
  - AZURE_BLUET
  - BRAIN_CORAL_BLOCK
  - BROWN_CONCRETE_POWDER
  - WAXED_OXIDIZED_CUT_COPPER_STAIRS
  - CHERRY_HANGING_SIGN
  - WARPED_STAIRS
  - SPORE_BLOSSOM
  - ORANGE_BED
  - ACACIA_HANGING_SIGN
  - SCAFFOLDING
  - RED_WALL_BANNER
  - DARK_OAK_STAIRS
  - BROWN_BANNER
  - DARK_OAK_DOOR
  - CHERRY_FENCE_GATE
  - CHERRY_SAPLING
  - TWISTING_VINES_PLANT
  - FIRE_CORAL_FAN
  - CHERRY_DOOR
  - SOUL_TORCH
  - GRAY_STAINED_GLASS_PANE
  - AZALEA
  - MAGENTA_BED
  - COBBLED_DEEPSLATE_STAIRS
  - MANGROVE_PROPAGULE
  - MANGROVE_WALL_HANGING_SIGN
  - GRAY_CARPET
  - PRISMARINE_BRICK_STAIRS
  - OAK_PRESSURE_PLATE
  - ANDESITE_STAIRS
  - BLUE_BED
  - BIG_DRIPLEAF
  - DARK_OAK_HANGING_SIGN
  - REDSTONE_LAMP
  - POLISHED_GRANITE_STAIRS
  - WARPED_WALL_HANGING_SIGN
  - WARPED_DOOR
  - MANGROVE_HANGING_SIGN
  - SPRUCE_TRAPDOOR
  - ACACIA_SAPLING
  - BIRCH_PRESSURE_PLATE
  - MANGROVE_BUTTON
  - BAMBOO
  - BIG_DRIPLEAF_STEM
  - RED_STAINED_GLASS_PANE
  - TUBE_CORAL
  - CYAN_WALL_BANNER
  - RED_NETHER_BRICK_STAIRS
  - ACACIA_BUTTON
  - BIRCH_SIGN
  - OXEYE_DAISY
  - WARPED_HANGING_SIGN
  - TWISTING_VINES
  - CYAN_CONCRETE_POWDER
  - DETECTOR_RAIL
  - CRIMSON_STAIRS
  - WARPED_SIGN
  - EXPOSED_CUT_COPPER_STAIRS
  - BROWN_WALL_BANNER
  - ACACIA_SIGN
  - WARPED_BUTTON
  - HANGING_ROOTS
  - BLUE_CONCRETE_POWDER
  - GLOW_LICHEN
  - SPRUCE_FENCE
  - LEVER
  - BUBBLE_CORAL_FAN
  - PURPLE_STAINED_GLASS_PANE
  - BIRCH_WALL_HANGING_SIGN
  - CRIMSON_FUNGUS
  - CRIMSON_HANGING_SIGN
  - NOTE_BLOCK
  - POLISHED_BLACKSTONE_BUTTON
  - RAIL
  - ORANGE_CARPET
  - OAK_FENCE_GATE
  - GRAY_CONCRETE_POWDER
  - ORANGE_WALL_BANNER
  - ALLIUM
  - DARK_OAK_WALL_HANGING_SIGN
  - WEATHERED_CUT_COPPER_STAIRS
  - MANGROVE_FENCE_GATE
  - PITCHER_PLANT
  - DARK_OAK_PRESSURE_PLATE
  - LILY_PAD
  - SPRUCE_SAPLING
  - REDSTONE_WIRE
  - WARPED_WALL_SIGN
  - CHERRY_FENCE
  - STONE_BUTTON
  - SPRUCE_BUTTON
  - SAND
  - JUNGLE_WALL_SIGN
  - JUNGLE_FENCE_GATE
  - QUARTZ_STAIRS
  - DARK_OAK_TRAPDOOR
  - YELLOW_STAINED_GLASS_PANE
  - JUNGLE_SAPLING
  - SPRUCE_STAIRS
  - DIORITE_WALL
  - WHITE_CONCRETE_POWDER
  - WITHER_ROSE
  - LADDER
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - MANGROVE_DOOR
  - RED_MUSHROOM
  - CORNFLOWER
  - JUNGLE_HANGING_SIGN
  - DIORITE_STAIRS
  - TRIPWIRE
  - LIGHT_BLUE_WALL_BANNER
  - ACACIA_PRESSURE_PLATE
  - RED_SANDSTONE_STAIRS
  - ACACIA_FENCE_GATE
  - ROSE_BUSH
  - NETHER_BRICK_WALL
  - BROWN_BED
  - GREEN_STAINED_GLASS_PANE
  - DARK_OAK_BUTTON
  - ACACIA_FENCE
  - LANTERN
  - DARK_OAK_SAPLING
  - LIGHT_GRAY_CONCRETE_POWDER
  - SANDSTONE_STAIRS
  - WHITE_BED
  - WALL_TORCH
  - SUSPICIOUS_SAND
  - DARK_OAK_SIGN
  - SMALL_DRIPLEAF
  - CACTUS
  - BAMBOO_DOOR
  - BRAIN_CORAL_FAN
  - CRIMSON_TRAPDOOR
  - PURPLE_CARPET
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - FIRE_CORAL
  - SPRUCE_FENCE_GATE
  - BAMBOO_FENCE_GATE
  - GRAY_BED
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - TUBE_CORAL_FAN
  - LIGHT_GRAY_BANNER
  - SUGAR_CANE
  - TUBE_CORAL_WALL_FAN
  - LIGHT_BLUE_CARPET
  - BIRCH_STAIRS
  - YELLOW_BANNER
  - CRIMSON_ROOTS
  - CRIMSON_FENCE_GATE
  - LIME_WALL_BANNER
  - LIGHT_BLUE_BED
  - WHITE_STAINED_GLASS_PANE
  - SOUL_WALL_TORCH
  - LIGHTNING_ROD
  - YELLOW_CARPET
  - BAMBOO_STAIRS
  - SPRUCE_DOOR
  - REDSTONE_WALL_TORCH
  - WARPED_ROOTS
  - BAMBOO_WALL_SIGN
  - YELLOW_WALL_BANNER
  - POLISHED_BLACKSTONE_BRICK_STAIRS
  - WARPED_FENCE_GATE
  - GREEN_WALL_BANNER
  - BIRCH_TRAPDOOR
  - HORN_CORAL_WALL_FAN
  - LIME_STAINED_GLASS_PANE
  - MANGROVE_FENCE
  - WHITE_WALL_BANNER
  - TUBE_CORAL_BLOCK
  - DEEPSLATE_TILE_WALL
  - ORANGE_TULIP
  - POPPY
  - SEA_PICKLE
  - ORANGE_BANNER
  - POLISHED_ANDESITE_STAIRS
  - SMOOTH_QUARTZ_STAIRS
  - PURPLE_BED
  - GRANITE_STAIRS
  - LIGHT_GRAY_WALL_BANNER
  - PINK_TULIP
  - OXIDIZED_CUT_COPPER_STAIRS
  - CHERRY_BUTTON
  - GRAY_WALL_BANNER
  - DARK_OAK_FENCE
  - MAGENTA_CARPET
  - DIRT_PATH
  - YELLOW_BED
  - PINK_BED
  - BROWN_CARPET
  - NETHER_PORTAL
  - WHITE_TULIP
  - POLISHED_BLACKSTONE_PRESSURE_PLATE
  - ANDESITE_WALL
  - SMOOTH_RED_SANDSTONE_STAIRS
  - CHAIN
  - PINK_CARPET
  - DEEPSLATE_TILE_STAIRS
  - OAK_BUTTON
  - GLASS_PANE
  - SPRUCE_WALL_SIGN
  - STONE_STAIRS
  - RED_CONCRETE_POWDER
  - WARPED_FUNGUS
  - NETHER_SPROUTS
  - GREEN_CONCRETE_POWDER
  - MANGROVE_PRESSURE_PLATE
  - BRICK_STAIRS
  - DEEPSLATE_BRICK_WALL
  - BROWN_MUSHROOM
  - BAMBOO_FENCE
  - COBBLED_DEEPSLATE_WALL
  - BAMBOO_WALL_HANGING_SIGN
  - TORCHFLOWER
  - SNOW
  - RED_SAND
  - LIGHT_BLUE_CONCRETE_POWDER
  - BIRCH_HANGING_SIGN
  - LARGE_AMETHYST_BUD
  - HORN_CORAL_BLOCK
  - PINK_WALL_BANNER
  - RED_TULIP
  - BLUE_BANNER
  - CUT_COPPER_STAIRS
  - GRAY_BANNER
  - DARK_PRISMARINE_STAIRS
  - JUNGLE_STAIRS
  - AMETHYST_CLUSTER
  - VINE
  - CYAN_BED
  - BUBBLE_CORAL_WALL_FAN
  - BAMBOO_HANGING_SIGN
  - GRAVEL
  - LIGHT_GRAY_CARPET
  - MOSSY_STONE_BRICK_STAIRS
  - STONE_BRICK_WALL
  - PURPLE_WALL_BANNER
  - MEDIUM_AMETHYST_BUD
  - JUNGLE_WALL_HANGING_SIGN
  - SANDSTONE_WALL
  - ACACIA_WALL_SIGN
  - ORANGE_STAINED_GLASS_PANE
  - SPRUCE_HANGING_SIGN
  - MUD_BRICK_STAIRS
  - RED_BED
  - JUNGLE_FENCE
  - PURPLE_CONCRETE_POWDER
  - WAXED_EXPOSED_CUT_COPPER_STAIRS
  - BLACK_CONCRETE_POWDER
  - DARK_OAK_FENCE_GATE
  - ACACIA_STAIRS
  - MUSHROOM_STEM
  - BIRCH_SAPLING
  - PINK_PETALS
  - POLISHED_DEEPSLATE_STAIRS
  - END_STONE_BRICK_STAIRS
  - POLISHED_BLACKSTONE_BRICK_WALL
  - BAMBOO_BUTTON
  - BLUE_WALL_BANNER
  - LIME_BED
  - MOSSY_COBBLESTONE_WALL
  - SPRUCE_PRESSURE_PLATE
  - SMALL_AMETHYST_BUD
  - DEEPSLATE_BRICK_STAIRS
  - CRIMSON_SIGN
  - WEEPING_VINES_PLANT
  - BAMBOO_SIGN
  - GREEN_BANNER
  - HORN_CORAL_FAN
  - GREEN_BED
  - BIRCH_BUTTON
  - MANGROVE_TRAPDOOR
  - FARMLAND
  - NETHER_BRICK_STAIRS
  - WAXED_WEATHERED_CUT_COPPER_STAIRS
  - PRISMARINE_WALL
  - WEEPING_VINES
  - JUNGLE_DOOR
  - LILY_OF_THE_VALLEY
  - PURPLE_BANNER
  - PEONY
  - CRIMSON_DOOR
  - PINK_CONCRETE_POWDER
  - MUD_BRICK_WALL
  - BIRCH_FENCE
  - ACTIVATOR_RAIL
  - MANGROVE_SIGN
  - WHITE_BANNER
  - TUFF_STAIRS
  - TUFF_SLAB
  - TUFF_WALL
  - POLISHED_TUFF_SLAB
  - POLISHED_TUFF_STAIRS
  - POLISHED_TUFF_WALL
  - TUFF_BRICK_SLAB
  - TUFF_BRICK_STAIRS
  - TUFF_BRICK_WALL
  - COPPER_DOOR
  - EXPOSED_COPPER_DOOR
  - WEATHERED_COPPER_DOOR
  - OXIDIZED_COPPER_DOOR
  - WAXED_COPPER_DOOR
  - WAXED_EXPOSED_COPPER_DOOR
  - WAXED_WEATHERED_COPPER_DOOR
  - WAXED_OXIDIZED_COPPER_DOOR
  - COPPER_TRAPDOOR
  - EXPOSED_COPPER_TRAPDOOR
  - WEATHERED_COPPER_TRAPDOOR
  - OXIDIZED_COPPER_TRAPDOOR
  - WAXED_COPPER_TRAPDOOR
  - WAXED_EXPOSED_COPPER_TRAPDOOR
  - WAXED_WEATHERED_COPPER_TRAPDOOR
  - WAXED_OXIDIZED_COPPER_TRAPDOOR